#!/usr/bin/env python3
"""Generates the database documents from the live JSON data, so the docs cannot drift from the game.

Writes docs/CHARACTER_DATABASE.md, TOWER_DATABASE.md, ENEMY_DATABASE.md, BOSS_DATABASE.md,
MAP_DATABASE.md and ASSET_LICENSES.md. Hand-written docs (README, GAME_DESIGN, ARCHITECTURE,
LORE_RESEARCH, TEST_REPORT, BUILD_REPORT, KNOWN_LIMITATIONS) are not touched.
"""
import json, os, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
os.makedirs(DOCS, exist_ok=True)

def load(rel):
    with open(os.path.join(ROOT, rel)) as f:
        return json.load(f)

CONF_LABEL = {
    "canon_confirmed": "confirmed canon",
    "supported": "supported",
    "uncertain": "uncertain",
    "fan_theory": "fan theory",
}

def conf(c):
    c = (c or "").strip()
    for key, label in CONF_LABEL.items():
        if c.startswith(key):
            return label
    return c or "unstated"

def write(name, text):
    path = os.path.join(DOCS, name)
    with open(path, "w") as f:
        f.write(text)
    print("wrote", name, "(%d lines)" % text.count("\n"))

BANNER = ("<!-- Generated by tools/gen_docs.py from the JSON in data/. Do not edit by hand; "
          "edit the data and regenerate. -->\n\n")

# ------------------------------------------------------------------ characters
def characters_doc():
    chars = load("data/lore/characters.json")["entries"]
    towers = {t["id"]: t for t in load("data/towers/towers.json")["towers"]}
    heroes = {h["id"]: h for h in load("data/heroes/heroes.json")["heroes"]}
    enemies = load("data/enemies/enemies.json")["enemies"]
    enemy_chars = set()
    for e in enemies:
        for s in e.get("skin_pool", []):
            enemy_chars.add(s)

    out = [BANNER, "# Character Database\n\n",
           "Every character researched for this project, what the sources say about them, and the "
           "gameplay role they were given. Confidence tiers are explained in "
           "[LORE_RESEARCH.md](LORE_RESEARCH.md).\n\n"]

    prot = [c for c in chars if c.get("protagonist")]
    anta = [c for c in chars if c.get("antagonist")]
    other = [c for c in chars if not c.get("protagonist") and not c.get("antagonist")]

    out.append("## Summary\n\n")
    out.append("| | Count |\n|---|---|\n")
    out.append("| Characters researched | %d |\n" % len(chars))
    out.append("| Protagonists | %d |\n" % len(prot))
    out.append("| Antagonists | %d |\n" % len(anta))
    out.append("| Playable as heroes | %d |\n" % len(heroes))
    out.append("| Deployable as towers | %d |\n" % len(towers))
    by_conf = collections.Counter(conf(c.get("confidence")) for c in chars)
    out.append("| Confidence | %s |\n\n" % ", ".join("%s %d" % (k, v) for k, v in by_conf.most_common()))

    def role_of(cid):
        bits = []
        if cid in heroes:
            bits.append("**Hero** — %s" % heroes[cid].get("role", ""))
        if cid in towers:
            bits.append("**Tower** — %s, %d ⬧" % (towers[cid].get("category", ""), towers[cid].get("cost", 0)))
        if cid in enemy_chars:
            bits.append("**Enemy skin**")
        return " · ".join(bits) if bits else "_Codex only_"

    def section(title, group, note):
        out.append("\n## %s\n\n%s\n" % (title, note))
        for c in sorted(group, key=lambda x: x.get("name", "")):
            cid = c.get("id", "")
            out.append("\n### %s\n\n" % c.get("name", cid))
            aliases = c.get("aliases") or []
            if aliases:
                out.append("*Also known as: %s*\n\n" % ", ".join(aliases))
            out.append("- **Role in the story:** %s\n" % c.get("role", "—"))
            out.append("- **In game:** %s\n" % role_of(cid))
            out.append("- **Confidence:** %s\n" % conf(c.get("confidence")))
            fac = c.get("faction") or []
            if fac:
                out.append("- **Factions:** %s\n" % ", ".join(fac))
            if c.get("first_appearance"):
                out.append("- **First appearance:** %s\n" % c["first_appearance"])
            arcs = c.get("major_arcs") or []
            if arcs:
                out.append("- **Major arcs:** %s\n" % ", ".join(arcs))
            eq = c.get("known_equipment") or []
            if eq:
                out.append("- **Known equipment:** %s\n" % "; ".join(eq))
            ab = c.get("known_abilities") or []
            if ab:
                out.append("- **Known abilities:** %s\n" % "; ".join(ab))
            ev = c.get("important_events") or []
            if ev:
                out.append("\n**Important events**\n\n")
                for e in ev:
                    out.append("- %s\n" % e)
            rel = c.get("important_relationships") or []
            if rel:
                out.append("\n**Relationships**\n\n")
                for r in rel:
                    out.append("- %s — %s *(%s)*\n" % (r.get("with", ""), r.get("type", ""), conf(r.get("confidence"))))
            if c.get("potential_gameplay_role"):
                out.append("\n**Gameplay interpretation:** %s\n" % c["potential_gameplay_role"])
            src = c.get("research_sources") or []
            if src:
                out.append("\n<details><summary>Sources (%d)</summary>\n\n" % len(src))
                for s in src:
                    out.append("- %s\n" % s)
                out.append("\n</details>\n")

    section("Protagonists", prot,
            "The four POV characters. The player controls exactly one per run.")
    section("Antagonists", anta,
            "Villains, tiered into enemies, elites, mini-bosses and bosses in "
            "[BOSS_DATABASE.md](BOSS_DATABASE.md).")
    section("Supporting characters", other,
            "Allies, civic leaders and minor figures. Most become towers.")
    return "".join(out)

# ------------------------------------------------------------------ towers
def towers_doc():
    towers = load("data/towers/towers.json")
    rels = load("data/characters/relationships.json")["relationships"]
    out = [BANNER, "# Tower Database\n\n",
           "All %d deployable characters with their full upgrade trees.\n\n" % len(towers["towers"]),
           "**The Gear Rule:** every tower has three upgrade paths. One path may be taken to tier 4 "
           "(its Signature upgrade), a second may reach tier 2, and the third stays at 0. You cannot "
           "max two paths.\n\n"]
    out.append("## At a glance\n\n")
    out.append("| Tower | Role | Cost | Damage | Range | Interval | Type | Notes |\n")
    out.append("|---|---|---|---|---|---|---|---|\n")
    for t in towers["towers"]:
        notes = []
        if t.get("detect_invisible"):
            notes.append("sees invisible")
        if t.get("hit_air"):
            notes.append("hits air")
        if t.get("income"):
            notes.append("income")
        if t.get("mercenary"):
            notes.append("unreliable")
        out.append("| **%s** | %s | %d ⬧ | %s | %s | %.2fs | %s | %s |\n" % (
            t.get("name"), t.get("category"), t.get("cost", 0), t.get("damage"), t.get("range"),
            t.get("attack_time", 1), t.get("damage_type"), ", ".join(notes) or "—"))
    for t in towers["towers"]:
        out.append("\n---\n\n## %s\n\n" % t.get("name"))
        out.append("*%s · %d emeralds · confidence: %s*\n\n" % (
            t.get("category"), t.get("cost", 0), conf(t.get("lore_confidence"))))
        out.append("%s\n\n" % t.get("lore", ""))
        out.append("**Base stats** — damage %s, range %s, one attack every %.2fs, %s damage, "
                   "%d pierce, %.1f splash, %d%% armor pierce, targets %s.\n\n" % (
            t.get("damage"), t.get("range"), t.get("attack_time", 1), t.get("damage_type"),
            t.get("pierce", 1), t.get("splash", 0.0), int(t.get("armor_pen", 0) * 100), t.get("targeting")))
        for p in t.get("paths", []):
            out.append("### %s\n\n" % p.get("name"))
            out.append("| Tier | Upgrade | Cost | Effect |\n|---|---|---|---|\n")
            for i, tier in enumerate(p.get("tiers", []), 1):
                out.append("| %d | **%s** | %d ⬧ | %s |\n" % (
                    i, tier.get("name"), tier.get("cost", 0), tier.get("desc", "")))
            out.append("\n")
        mine = [r for r in rels if t["id"] in (r.get("a"), r.get("b"))]
        if mine:
            out.append("### Relationship bonds\n\n")
            for r in mine:
                other = r["b"] if r["a"] == t["id"] else r["a"]
                out.append("- **%s** (with `%s`) — %s\n" % (r.get("name"), other, r.get("basis", "")))
            out.append("\n")
    return "".join(out)

# ------------------------------------------------------------------ enemies
def enemies_doc():
    data = load("data/enemies/enemies.json")
    factions = load("data/enemies/factions.json")["factions"]
    enemies = data["enemies"]
    out = [BANNER, "# Enemy Database\n\n",
           "All %d enemy types. Every entry states why it exists as a gameplay problem — the brief "
           "required that no enemy be decorative.\n\n" % len(enemies)]

    out.append("## The Chungie gear ladder\n\n")
    out.append("The core enemy. 'Chungie' is community slang for an under-geared player; here the "
               "tiers are Minecraft gear tiers. When a layer's health is depleted the gear visibly "
               "breaks off and the unit keeps running in whatever is underneath, carrying overflow "
               "damage down with it. This is the game's original take on layered enemies — it is "
               "built on gear progression, not on colour.\n\n")
    out.append("| Tier | Enemy | HP | Speed | Armor | Threat | Pays | Breaks into | Gear |\n")
    out.append("|---|---|---|---|---|---|---|---|---|\n")
    for e in enemies:
        if e.get("category") != "chungie":
            continue
        gear = ", ".join("%s %s" % (k, str(v).replace("_", " ")) for k, v in (e.get("armor") or {}).items()) or "none"
        out.append("| %d | **%s** | %s | %s | %d%% | %s | %s ⬧ | %s | %s |\n" % (
            e.get("tier", 0), e.get("name"), e.get("hp"), e.get("speed"),
            int(e.get("armor_pct", 0) * 100), e.get("threat"), e.get("reward"),
            e.get("downgrade_to") or "—", gear))

    groups = collections.OrderedDict([
        ("special", "Special enemies"), ("siege", "Siege"), ("structure", "Structures"),
        ("mini_boss", "Mini-bosses"), ("boss", "Bosses"), ("vehicle", "Vehicles"),
    ])
    for cat, title in groups.items():
        rows = [e for e in enemies if e.get("category") == cat]
        if not rows:
            continue
        out.append("\n## %s\n\n" % title)
        for e in rows:
            out.append("\n### %s\n\n" % e.get("name"))
            out.append("%s\n\n" % e.get("codex", ""))
            out.append("**Why it exists:** %s\n\n" % e.get("gameplay_reason", ""))
            flags = e.get("flags") or []
            out.append("| Tier | HP | Speed | Armor | Threat | Reward | Flags |\n|---|---|---|---|---|---|---|\n")
            out.append("| %s | %s | %s | %d%% | %s | %s ⬧ | %s |\n\n" % (
                e.get("tier"), e.get("hp"), e.get("speed"), int(e.get("armor_pct", 0) * 100),
                e.get("threat"), e.get("reward"), ", ".join(flags) or "—"))
            ab = e.get("abilities") or []
            if ab:
                out.append("Abilities: %s\n\n" % ", ".join("`%s`" % a.get("type") for a in ab))

    out.append("\n## Factions\n\n")
    out.append("A faction re-skins and modifies a whole map: enemy appearance, stat multipliers, which "
               "special units appear, the boss, the music and the announcer lines.\n\n")
    out.append("| Faction | HP | Speed | Reward | Special units | Boss |\n|---|---|---|---|---|---|\n")
    for f in factions:
        out.append("| **%s** | ×%.2f | ×%.2f | ×%.2f | %s | %s |\n" % (
            f.get("name"), f.get("hp_mult", 1), f.get("speed_mult", 1), f.get("reward_mult", 1),
            ", ".join(f.get("special_units", [])) or "—", f.get("boss") or "—"))

    out.append("\n## Damage and armor\n\n")
    out.append("```\neffective = raw × (1 − armor_pct × (1 − armor_pen))\n"
               "effective = max(effective, raw × 0.10)      # armor can never fully negate a hit\n```\n\n")
    out.append("Damage types then modify the result against shields and structures:\n\n")
    out.append("| Type | vs shield | vs structure | Ignores armor |\n|---|---|---|---|\n")
    for k, v in load("data/characters/weapons_catalog.json")["damage_types"].items():
        out.append("| %s | ×%.2f | ×%.2f | %s |\n" % (
            k, v.get("vs_shield", 1), v.get("vs_structure", 1), "yes" if v.get("ignores_armor") else "no"))
    return "".join(out)

# ------------------------------------------------------------------ bosses
def bosses_doc():
    bosses = load("data/bosses/bosses.json")["bosses"]
    lore = load("data/lore/bosses.json")["entries"]
    enemies = {e["id"]: e for e in load("data/enemies/enemies.json")["enemies"]}
    out = [BANNER, "# Boss Database\n\n",
           "Bosses are multi-phase encounters whose structure comes from what actually happened in "
           "the story. Each phase names the event it is built on and the mechanic that represents "
           "it — the event is researched, the mechanic is game design.\n\n"]
    for b in bosses:
        e = enemies.get(b.get("enemy"), {})
        out.append("## %s\n\n*%s*\n\n" % (b.get("name"), b.get("title", "")))
        out.append("- **Maps:** %s\n" % ", ".join(b.get("maps", [])))
        out.append("- **Health:** %s · **Armor:** %d%% · **Threat if it reaches the base:** %s\n" % (
            e.get("hp", "—"), int(e.get("armor_pct", 0) * 100), e.get("threat", "—")))
        out.append("- **Reward:** %s emeralds\n" % b.get("reward_emeralds"))
        out.append("- **Confidence:** %s\n\n" % conf(b.get("confidence")))
        if b.get("intro_line"):
            out.append("> %s\n\n" % b["intro_line"])
        out.append("### Phases\n\n")
        for p in b.get("phases", []):
            out.append("#### %d. %s\n\n" % (p.get("index", 0), p.get("name")))
            out.append("*%s*\n\n" % p.get("desc", ""))
            out.append("- **Basis in the story:** %s\n" % p.get("basis", ""))
            out.append("- **Mechanic:** %s\n" % p.get("mechanic", ""))
            if p.get("minions"):
                out.append("- **Reinforcements:** %s (budget %s, one every %ss)\n" % (
                    ", ".join(p["minions"]), p.get("budget"), p.get("spawn_interval")))
            out.append("\n")
        src = b.get("sources") or []
        if src:
            out.append("<details><summary>Sources</summary>\n\n")
            for s in src:
                out.append("- %s\n" % s)
            out.append("\n</details>\n\n")
    out.append("\n## Antagonist tiering\n\n")
    out.append("Every researched villain, and the role they were judged right for. Only the "
               "`implemented` ones are in the vertical slice.\n\n")
    out.append("| Villain | Tier | Implemented | Basis |\n|---|---|---|---|\n")
    for e in lore:
        out.append("| %s | %s | %s | %s |\n" % (
            e.get("character"), e.get("tier"), "yes" if e.get("implemented") else "designed only",
            "; ".join(e.get("canon_basis", []))[:120]))
    return "".join(out)

# ------------------------------------------------------------------ maps
def maps_doc():
    maps = load("data/maps/maps.json")["maps"]
    locs = {l["id"]: l for l in load("data/lore/locations.json")["entries"]}
    out = [BANNER, "# Map Database\n\n",
           "Maps are built procedurally from the definitions in `data/maps/maps.json` — terrain "
           "patches, a path polyline, build zones, structures and lighting.\n\n"]
    out.append("## Implemented\n\n")
    for m in maps:
        waves = load(m["waves"].replace("res://", "")) if m.get("waves") else {"waves": []}
        loc = locs.get(m.get("location"), {})
        out.append("\n### %s\n\n*%s*\n\n" % (m.get("name"), m.get("subtitle", "")))
        out.append("- **Location:** %s (%s)\n" % (loc.get("name", "—"), conf(loc.get("confidence"))))
        out.append("- **Arc:** %s · **Enemy faction:** %s\n" % (m.get("arc"), m.get("faction")))
        if m.get("boss"):
            out.append("- **Boss:** %s\n" % m["boss"])
        if m.get("mini_boss"):
            out.append("- **Mini-boss:** %s\n" % m["mini_boss"])
        out.append("- **Waves:** %d · **Starting emeralds:** %d · **Lives:** %d\n" % (
            len(waves.get("waves", [])), m.get("start_emeralds", 0), m.get("lives", 0)))
        out.append("- **Build zones:** %d · **Path points:** %d · **Difficulty:** %s\n" % (
            len(m.get("build_zones", [])), len(m.get("path", [])), m.get("difficulty")))
        out.append("- **Unlocked from the start:** %s\n\n" % ("yes" if m.get("unlocked") else "no"))
        if loc.get("description"):
            out.append("%s\n\n" % loc["description"])
        out.append("**Wave list**\n\n| # | Wave | Reward | Composition |\n|---|---|---|---|\n")
        for i, w in enumerate(waves.get("waves", []), 1):
            comp = ", ".join("%d× %s" % (g.get("count", 0), g.get("enemy", "")) for g in w.get("groups", []))
            events = [e.get("type") for e in w.get("events", [])]
            if events:
                comp += (" " if comp else "") + "*(events: %s)*" % ", ".join(events)
            out.append("| %d | %s%s | %d ⬧ | %s |\n" % (
                i, w.get("name"), " **(BOSS)**" if w.get("boss") else "", w.get("reward", 0), comp or "—"))
        out.append("\n")
    out.append("\n## Researched candidates not yet built\n\n")
    out.append("Locations from the research with a note on what each would become. These are design "
               "targets, not implemented content.\n\n")
    out.append("| Location | Era | Controlled by | Map potential |\n|---|---|---|---|\n")
    for l in locs.values():
        if l.get("map_ids"):
            continue
        out.append("| **%s** | %s | %s | %s |\n" % (
            l.get("name"), l.get("era", "—"), ", ".join(l.get("controlled_by", [])) or "—",
            l.get("map_potential", "—")))
    return "".join(out)

# ------------------------------------------------------------------ assets
def assets_doc():
    m = load("data/asset_manifest.json")
    out = [BANNER, "# Asset Licenses and Provenance\n\n"]
    out.append("Every asset shipped in this repository, where it came from, and what may be done "
               "with it.\n\n")
    out.append("## Policy\n\n")
    for n in m.get("notes", []):
        out.append("- %s\n" % n)
    s = m.get("summary", {})
    out.append("\n## Summary\n\n| | Count |\n|---|---|\n")
    out.append("| Total assets | %d |\n" % s.get("total", 0))
    for k, v in sorted(s.get("by_type", {}).items()):
        out.append("| %s | %d |\n" % (k.capitalize(), v))
    out.append("| Placeholders awaiting a real asset | %d |\n\n" % s.get("placeholders", 0))

    out.append("## Missing assets\n\n")
    out.append("The following are **procedurally generated placeholders**, not the real characters' "
               "skins. Supplying a licensed skin PNG at `assets/skins/<id>.png` or "
               "`user://skins/<id>.png` replaces it with no code change. See the README.\n\n")
    ph = [a for a in m["assets"] if a.get("placeholder") and a.get("type") == "skin"]
    out.append("| Character id | Model | File |\n|---|---|---|\n")
    for a in sorted(ph, key=lambda x: x["id"]):
        out.append("| `%s` | %s | `%s` |\n" % (a["id"], a.get("model", "classic"), a["asset"]))

    out.append("\n## Full manifest\n\n")
    out.append("| Asset | Type | Source | Creator | License / permission | Usage |\n")
    out.append("|---|---|---|---|---|---|\n")
    for a in m["assets"]:
        out.append("| `%s` | %s | %s | %s | %s | %s |\n" % (
            a.get("asset"), a.get("type"), a.get("source"), a.get("creator"),
            a.get("license"), a.get("usage")))
    out.append("\n## What is deliberately absent\n\n")
    out.append("- **No Minecraft/Mojang assets.** All block textures, item models and character "
               "geometry are original, generated by `tools/gen_assets.py`. The character proportions "
               "follow the well-known humanoid layout so that community skin files map correctly, "
               "but no Mojang file is included or required.\n")
    out.append("- **No creator-associated music.** All audio is synthesised from oscillators by "
               "`tools/gen_audio.py`. No track references or samples music associated with any real "
               "person.\n")
    out.append("- **No scraped assets.** Nothing was downloaded from a third-party site. The build "
               "tools generate every shipped asset from code.\n")
    return "".join(out)

def main():
    write("CHARACTER_DATABASE.md", characters_doc())
    write("TOWER_DATABASE.md", towers_doc())
    write("ENEMY_DATABASE.md", enemies_doc())
    write("BOSS_DATABASE.md", bosses_doc())
    write("MAP_DATABASE.md", maps_doc())
    write("ASSET_LICENSES.md", assets_doc())

if __name__ == "__main__":
    main()
